#!/bin/bash
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli sch export svg --output docs/schem PCB/flopper_one/*.kicad_sch
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb export svg --output docs/pcb.svg --theme _builtin_default PCB/flopper_one/*.kicad_pcb --layers "F.Cu,B.Cu,F.Silkscreen,B.Silkscreen,Edge.Cuts,F.Fab,B.Fab"


# Extract viewBox dimensions
VIEWBOX=$(grep -o 'viewBox="[^"]*"' docs/pcb.svg | sed 's/viewBox="[^ ]* [^ ]* \([^ ]*\) \([^"]*\)"/\1 \2/')
WIDTH=$(echo $VIEWBOX | cut -d' ' -f1)
HEIGHT=$(echo $VIEWBOX | cut -d' ' -f2)

# Add background color
sed -i '' "/<desc>Image generated by PCBNEW <\/desc>/a\\
<!-- Background rectangle -->\\
<rect x=\"0\" y=\"0\" width=\"$WIDTH\" height=\"$HEIGHT\" fill=\"#001124\"/>
" docs/pcb.svg