#!/bin/bash
set -euo pipefail

KICAD_CLI="/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli"

SCH_FILES=(PCB/flopper_one/*.kicad_sch)
PCB_FILES_RAW=(PCB/flopper_one/*.kicad_pcb)
PCB_FILES=()
for f in "${PCB_FILES_RAW[@]}"; do
  case "$f" in
    */_autosave-*.kicad_pcb) ;;
    *) PCB_FILES+=("$f") ;;
  esac
done

if [[ ${#SCH_FILES[@]} -ne 1 ]]; then
  echo "Expected exactly 1 schematic (*.kicad_sch) in PCB/flopper_one/, found ${#SCH_FILES[@]}" >&2
  printf '  %s\n' "${SCH_FILES[@]}" >&2
  exit 1
fi

if [[ ${#PCB_FILES[@]} -ne 1 ]]; then
  echo "Expected exactly 1 board (*.kicad_pcb) in PCB/flopper_one/, found ${#PCB_FILES[@]}" >&2
  printf '  %s\n' "${PCB_FILES[@]}" >&2
  exit 1
fi

SCH_FILE="${SCH_FILES[0]}"
PCB_FILE="${PCB_FILES[0]}"

"$KICAD_CLI" sch export svg --output docs/schem "$SCH_FILE"
"$KICAD_CLI" pcb export svg --output docs/pcb.svg --layers "F.Cu,B.Cu,F.Silkscreen,B.Silkscreen,Edge.Cuts,F.Fab,B.Fab" "$PCB_FILE"

sed -i '' 's/fill:#4D7FC4; fill-opacity:1.0000/fill:#4D7FC4; fill-opacity:0.6/g' docs/pcb.svg


sed -i '' 's/fill:#C83434; fill-opacity:1.0000/fill:#C83434; fill-opacity:0.6/g' docs/pcb.svg
# Extract viewBox dimensions
VIEWBOX=$(grep -o 'viewBox="[^"]*"' docs/pcb.svg | sed 's/viewBox="[^ ]* [^ ]* \([^ ]*\) \([^"]*\)"/\1 \2/')
WIDTH=$(echo $VIEWBOX | cut -d' ' -f1)
HEIGHT=$(echo $VIEWBOX | cut -d' ' -f2)

# Add background color
sed -i '' "/<desc>Image generated by PCBNEW <\/desc>/a\\
<!-- Background rectangle -->\\
<rect x=\"0\" y=\"0\" width=\"$WIDTH\" height=\"$HEIGHT\" fill=\"#001124\"/>
" docs/pcb.svg


"$KICAD_CLI" pcb export step --output CAD/flopper_one.step "$PCB_FILE"

"$KICAD_CLI" pcb render \
  --output docs/pcb_3d_front.png \
  --side top \
  --width 1920 --height 1080 \
  --zoom 1.2 \
  --quality high \
  --preset follow_plot_settings \
  --use-board-stackup-colors \
  "$PCB_FILE"

"$KICAD_CLI" pcb render \
  --output docs/pcb_3d_back.png \
  --side bottom \
  --width 1920 --height 1080 \
  --zoom 1.2 \
  --quality high \
  --preset follow_plot_settings \
  --use-board-stackup-colors \
  "$PCB_FILE"

rm -f PCB/flopper_one/gerbers/*.gbr
"$KICAD_CLI" pcb export gerbers \
  --output PCB/flopper_one/gerbers/ \
    --no-protel-ext \
  --layers "F.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts" \
  "$PCB_FILE"
"$KICAD_CLI" pcb export drill \
  --output PCB/flopper_one/gerbers/ \
  --format excellon \
  "$PCB_FILE"


rm PCB/flopper_one/flopper_one_gerbers.zip
zip -j PCB/flopper_one/flopper_one_gerbers.zip PCB/flopper_one/gerbers/*.*r*

# blender "CAD/flopper.blend" --python "CAD/blender_export.py" --quit