#!/bin/bash
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli sch export svg --output docs/schem PCB/flopper_one/*.kicad_sch
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb export svg --output docs/pcb.svg --theme _builtin_default PCB/flopper_one/*.kicad_pcb --layers "F.Cu,B.Cu,F.Silkscreen,B.Silkscreen,Edge.Cuts,F.Fab,B.Fab"

sed -i '' 's/fill:#4D7FC4; fill-opacity:1.0000/fill:#4D7FC4; fill-opacity:0.6/g' docs/pcb.svg


sed -i '' 's/fill:#C83434; fill-opacity:1.0000/fill:#C83434; fill-opacity:0.6/g' docs/pcb.svg
# Extract viewBox dimensions
VIEWBOX=$(grep -o 'viewBox="[^"]*"' docs/pcb.svg | sed 's/viewBox="[^ ]* [^ ]* \([^ ]*\) \([^"]*\)"/\1 \2/')
WIDTH=$(echo $VIEWBOX | cut -d' ' -f1)
HEIGHT=$(echo $VIEWBOX | cut -d' ' -f2)

# Add background color
sed -i '' "/<desc>Image generated by PCBNEW <\/desc>/a\\
<!-- Background rectangle -->\\
<rect x=\"0\" y=\"0\" width=\"$WIDTH\" height=\"$HEIGHT\" fill=\"#001124\"/>
" docs/pcb.svg


/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb export step --output CAD/flopper_one.step PCB/flopper_one/*.kicad_pcb

# 3D render - front vie
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb render --output docs/pcb_3d_front.png --side top --width 1920 --height 1080 --zoom 1.2 PCB/flopper_one/*.kicad_pcb

# 3D render - back view
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb render --output docs/pcb_3d_back.png --side bottom --width 1920 --height 1080 --zoom 1.2 PCB/flopper_one/*.kicad_pcb

rm PCB/flopper_one/gerbers/*.gbr
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb export gerbers \
  --output PCB/flopper_one/gerbers/ \
    --no-protel-ext \
  --layers "F.Cu,B.Cu,F.Paste,B.Paste,F.Silkscreen,B.Silkscreen,F.Mask,B.Mask,Edge.Cuts" \
  PCB/flopper_one/*.kicad_pcb
/Applications/KiCad/KiCad.app/Contents/MacOS/kicad-cli pcb export drill \
  --output PCB/flopper_one/gerbers/ \
  --format excellon \
  PCB/flopper_one/*.kicad_pcb


rm PCB/flopper_one/flopper_one_gerbers.zip
zip -j PCB/flopper_one/flopper_one_gerbers.zip PCB/flopper_one/gerbers/*.*r*